<a href="https://colab.research.google.com/github/jimhhh898989/2022_SummerDL/blob/main/class1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch
import numpy as np

In [ ]:
tensor = torch.rand(2,3)
matrix = np.random.rand(2,3)
print(f"Tensor:\n {tensor}")
print(f"Matrix:\n {matrix}")

Tensor:
 tensor([[0.9596, 0.1535, 0.7393],
        [0.8787, 0.6564, 0.2319]])
Matrix:
 [[0.81523117 0.3893448  0.68097443]
 [0.45075004 0.72112311 0.67144527]]


In [ ]:
tensor = torch.zeros(2,3)
matrix = np.zeros((2,3))
print(f"Tensor:\n {tensor}")
print(f"Matrix:\n {matrix}")

Tensor:
 tensor([[0., 0., 0.],
        [0., 0., 0.]])
Matrix:
 [[0. 0. 0.]
 [0. 0. 0.]]


In [ ]:
tensor = torch.ones(2,3)
matrix = np.ones((2,3))
print(f"Tensor:\n {tensor}")
print(f"Matrix:\n {matrix}")

Tensor:
 tensor([[1., 1., 1.],
        [1., 1., 1.]])
Matrix:
 [[1. 1. 1.]
 [1. 1. 1.]]


In [ ]:
print(f"Tensor:\n {tensor.dtype}")
print(f"Matrix:\n {matrix.dtype}")

Tensor:
 torch.float32
Matrix:
 float64


In [ ]:
print(f"Tensor:\n {tensor.size()}") # method
print(f"Tensor:\n {tensor.shape}")  # attribute
print(f"Matrix:\n {matrix.shape}")

Tensor:
 torch.Size([2, 3])
Tensor:
 torch.Size([2, 3])
Matrix:
 (2, 3)


In [ ]:
# list to torch
tensor = torch.tensor([2.3, 1.2, 5.7])
print(f"Tensor:\n {tensor.size()}")
# list to numpy
matrix = np.array([2.3, 1.2, 5.7])
print(f"Matrix:\n {matrix.shape}")

Tensor:
 torch.Size([3])
Matrix:
 (3,)


In [ ]:
# numpy <=> torch
tensor = torch.tensor([1, 2, 3])
matrix = np.array([1, 2, 3])
print(torch.from_numpy(matrix))
print(tensor.numpy())

tensor([1, 2, 3])
[1 2 3]


In [ ]:
# call by reference
tensor = torch.tensor([1, 2, 3])
matrix = tensor.numpy()

tensor += 1
print(tensor)
print(matrix)

tensor([2, 3, 4])
[2 3 4]


In [ ]:
# operator 
t1 = torch.tensor([2.3, 1.2, 5.7])
t2 = torch.tensor([3.2, 2.8, 7.8])
print(torch.add(t1, t2)) # t1 + t2
print(torch.sub(t1, t2)) # t1 - t2
print(torch.mul(t1, t2)) # t1 * t2
print(torch.div(t1, t2)) # t1 / t2

tensor([ 5.5000,  4.0000, 13.5000])
tensor([-0.9000, -1.6000, -2.1000])
tensor([ 7.3600,  3.3600, 44.4600])
tensor([0.7188, 0.4286, 0.7308])


In [ ]:
# slice
tensor = torch.rand(5,3)
print(tensor)
print(tensor[:,1:3]) # 含前不含後
print(tensor[1,1].item())

tensor([[0.8685, 0.0089, 0.5715],
        [0.1306, 0.2420, 0.0258],
        [0.1397, 0.3621, 0.0224],
        [0.8908, 0.2101, 0.0264],
        [0.7298, 0.0880, 0.0264]])
tensor([[0.0089, 0.5715],
        [0.2420, 0.0258],
        [0.3621, 0.0224],
        [0.2101, 0.0264],
        [0.0880, 0.0264]])
0.2419639229774475


In [ ]:
# view
tensor = torch.rand(2,6)
print(tensor)
print(tensor.view(3,4))
print(tensor.view(12))
print(tensor.view(12,1))
print(tensor.view(1,12))
print(tensor.view(-1,3)) # 全部除以後面的等於前面的維度
print(tensor)

tensor([[0.9833, 0.3432, 0.5205, 0.1823, 0.9415, 0.0677],
        [0.5227, 0.4199, 0.5462, 0.2893, 0.3536, 0.5471]])
tensor([[0.9833, 0.3432, 0.5205, 0.1823],
        [0.9415, 0.0677, 0.5227, 0.4199],
        [0.5462, 0.2893, 0.3536, 0.5471]])
tensor([0.9833, 0.3432, 0.5205, 0.1823, 0.9415, 0.0677, 0.5227, 0.4199, 0.5462,
        0.2893, 0.3536, 0.5471])
tensor([[0.9833],
        [0.3432],
        [0.5205],
        [0.1823],
        [0.9415],
        [0.0677],
        [0.5227],
        [0.4199],
        [0.5462],
        [0.2893],
        [0.3536],
        [0.5471]])
tensor([[0.9833, 0.3432, 0.5205, 0.1823, 0.9415, 0.0677, 0.5227, 0.4199, 0.5462,
         0.2893, 0.3536, 0.5471]])
tensor([[0.9833, 0.3432, 0.5205],
        [0.1823, 0.9415, 0.0677],
        [0.5227, 0.4199, 0.5462],
        [0.2893, 0.3536, 0.5471]])
tensor([[0.9833, 0.3432, 0.5205, 0.1823, 0.9415, 0.0677],
        [0.5227, 0.4199, 0.5462, 0.2893, 0.3536, 0.5471]])


In [ ]:
# reshape, view 完全相同
tensor = torch.rand(2,6)
print(tensor)
print(tensor.reshape(3,4))
print(tensor.reshape(12))
print(tensor.reshape(12,1))
print(tensor.reshape(1,12))
print(tensor.reshape(-1,3)) # 全部除以後面的等於前面的維度
print(tensor)

tensor([[0.0923, 0.7465, 0.1151, 0.1830, 0.5052, 0.1694],
        [0.2464, 0.2285, 0.7263, 0.3876, 0.8085, 0.5469]])
tensor([[0.0923, 0.7465, 0.1151, 0.1830],
        [0.5052, 0.1694, 0.2464, 0.2285],
        [0.7263, 0.3876, 0.8085, 0.5469]])
tensor([0.0923, 0.7465, 0.1151, 0.1830, 0.5052, 0.1694, 0.2464, 0.2285, 0.7263,
        0.3876, 0.8085, 0.5469])
tensor([[0.0923],
        [0.7465],
        [0.1151],
        [0.1830],
        [0.5052],
        [0.1694],
        [0.2464],
        [0.2285],
        [0.7263],
        [0.3876],
        [0.8085],
        [0.5469]])
tensor([[0.0923, 0.7465, 0.1151, 0.1830, 0.5052, 0.1694, 0.2464, 0.2285, 0.7263,
         0.3876, 0.8085, 0.5469]])
tensor([[0.0923, 0.7465, 0.1151],
        [0.1830, 0.5052, 0.1694],
        [0.2464, 0.2285, 0.7263],
        [0.3876, 0.8085, 0.5469]])
tensor([[0.0923, 0.7465, 0.1151, 0.1830, 0.5052, 0.1694],
        [0.2464, 0.2285, 0.7263, 0.3876, 0.8085, 0.5469]])
